services:
  facade-service:
    build: ./facade
    ports:
      - "8080:8000"
    depends_on:
      - logging-service
      - counter-service

  logging-service:
    build: ./logging_service
    ports:
      - "8081:8000"

  counter-service:
    build: ./counter_service
    ports:
      - "8082:8000"