apiVersion: v1
kind: Service
metadata:
  name: facade-service
spec:
  type: NodePort
  selector:
    app: facade
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facade
  template:
    metadata:
      labels:
        app: facade
    spec:
      containers:
      - name: facade
        image: my-facade-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: banking-config