version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: bank-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"

  hazelcast:
    image: hazelcast/hazelcast:5.3.0
    deploy:
      replicas: 3

  config-server:
    build: ./config_server
    image: my-config-server
    container_name: config-app
    ports:
      - "8000:8000"

  facade-service:
    build: ./facade
    image: my-facade-service
    container_name: facade-app
    ports:
      - "8080:8000"
    environment:
      - CONFIG_SERVER=http://config-server:8000
    depends_on:
      - config-server
      - hazelcast

  logging-1:
    build: ./logging_service
    image: my-logging-service
    container_name: logging-node-1
    environment:
      - HZ_ADDRESSES=hazelcast:5701
      - SERVICE_NAME=logging-1
      - SERVICE_URL=http://logging-1:8000 
    ports:
      - "8081:8000"
    depends_on:
      - config-server
      - hazelcast

  logging-2:
    image: my-logging-service
    container_name: logging-node-2
    environment:
      - HZ_ADDRESSES=hazelcast:5701
      - SERVICE_NAME=logging-2
      - SERVICE_URL=http://logging-2:8000
    ports:
      - "8082:8000"
    depends_on:
      - config-server
      - hazelcast

  logging-3:
    image: my-logging-service
    container_name: logging-node-3
    environment:
      - HZ_ADDRESSES=hazelcast:5701
      - SERVICE_NAME=logging-3
      - SERVICE_URL=http://logging-3:8000
    ports:
      - "8083:8000"
    depends_on:
      - config-server
      - hazelcast

  counter-service:
    build: ./counter_service
    image: my-counter-service
    container_name: counter-app
    ports:
      - "8084:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-db:5432/bank_db
    depends_on:
      - postgres-db
      - config-server
      - hazelcast